### ISSUE TITLE
guard-delayed.gemspec needs updating

### ISSUE THREAD

**Issue by guapolo** [suranyami/guard-delayed#15]
Hi,
I think the gemspec needs to update delayed_job version dependendency to

     s.add_dependency 'delayed_job', '>= 3'

so it can be compatible with rails 4.2, delayed_job_active_record 4.1.1 and delayed_job 4.1.2.

Thanks.

**Comment by suranyami** [comment]
Done. Somehow, I already did this ages ago and forgot to push and rebuild the gems.

Sorry about that everyone.
